services:
  assetopsbench:
    platform: linux/amd64
    image: quay.io/assetopsbench/assetopsbench-extra
#    build:
#      context: .
#      dockerfile: Dockerfile
    volumes:
      - ../scenarios/:/home/scenarios/  # location to all utterances
      - ./run_plan_execute.py:/home/run_plan_execute.py # your python script to run it all
      - ./entrypoint.sh:/home/entrypoint.sh # your bash script to run it all
    env_file:
      - .env
    command: ["sh", "/home/entrypoint.sh" ]
  couchdb:
    image: couchdb:3.5
    restart: always
    ports:
      - "5984:5984"
    env_file:
      - .env
    volumes:
      - couchdb-data:/opt/couchdb/data  # location to couchdb data
      - ./couchdb_setup.sh:/opt/couchdb/etc/couchdb_setup.sh # your bash script to create couchdb out of raw data
      - ../src/assetopsbench/sample_data:/sample_data # location to raw (JSON/CSV) data for I/O
    command: ["sh", "/opt/couchdb/etc/couchdb_setup.sh" ]

volumes:
   couchdb-data: {}
